---
- name: crete inventory
  hosts: localhost
  gather_facts: false
  ignore_errors: true

  tasks:
  - name: create empty file
    file:
      path: "/root/ansible/inventory.list"
      state: touch

  - name: block in file
    blockinfile:
      path: "/root/ansible/inventory.list"
      block: |
        [all]
        10.0.1.10
        10.0.1.20
        10.0.1.21
        10.0.1.22

        [cout]
        10.0.1.10

        [web]
        10.0.1.20

        [was]
        10.0.1.21

        [db]
        10.0.1.22

        [nodes]
        10.0.1.20
        10.0.1.21
        10.0.1.22